permalink:           pretty

# Setup
title:               Kariem Hussein
tagline:             "Github Journal"
description:         "At this location you can find a collection of my thoughts and experiences related to my work as a developer."
url:                 https://kariem.github.io
paginate:            6
paginate_path:       "/p/:num"

author:
  name:              Kariem Hussein
  url:               https://kariem.github.io
  email:             kariem.hussein@gmail.com

gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
